# === Dev (hot-reload) ===
FROM node:20-alpine AS dev
WORKDIR /app
COPY package*.json ./
RUN npm install
USER node
EXPOSE 3000
CMD ["npm", "run", "dev"]

# Faza 1: Build
FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci --omit=dev

COPY . .

# Faza 2: Runtime
FROM nginx:1.27-alpine AS runtime

RUN apk update && apk upgrade --no-cache

COPY --from=builder /app/src/public /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

RUN addgroup -S appgroup && adduser -S appuser -G appgroup \
    && chown -R appuser:appgroup /usr/share/nginx/html \
    && chown -R appuser:appgroup /var/cache/nginx \
    && chown -R appuser:appgroup /var/log/nginx \
    && touch /var/run/nginx.pid \
    && chown appuser:appgroup /var/run/nginx.pid

USER appuser

EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]
