# === Dev (hot-reload) ===
FROM node:20-alpine AS dev
WORKDIR /app
COPY package*.json ./
RUN npm install
USER node
CMD ["npm", "run", "dev"]

# Faza 1: Build
FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci --omit=dev

COPY . .

# Faza 2: Runtime
FROM node:20-alpine AS runtime

RUN apk update && apk upgrade --no-cache

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app .

RUN addgroup -S appgroup && adduser -S appuser -G appgroup
USER appuser

CMD ["node", "src/worker.js"]
